name: Pull Request
on:
  pull_request:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:v0.38.0
    steps:
      - name: Lint markdown files
        run: markdownlint "content/**/*.md"
